import { ClerkProvider } from "@clerk/nextjs";   //ClerkProvider we wrap it around the layout
import { dark } from "@clerk/themes";            //Dark theme for clerk forms, we pass it to ClerkProvider
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
/* components that will be used inside the layout so they can be part of every page by default */
import LeftSidebar from "@/components/shared/LeftSidebar";
import Bottombar from "@/components/shared/Bottombar";
import RightSidebar from "@/components/shared/RightSidebar";
import Topbar from "@/components/shared/Topbar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Threads App",
  description: "Generated by create next app",
};

                                                         //children Typescript type
export default function RootLayout({children}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider appearance={{ baseTheme: dark }}>
      <html lang="en">
        <body className={inter.className}>
          <Topbar />
          <main className="flex flex-row">
            <LeftSidebar />
            <section className="main-container"> <div className="w-full max-w-4xl">{children}</div> </section>            
            <RightSidebar />
          </main>
          <Bottombar />
        </body>
      </html>
    </ClerkProvider>
  );
}
